### ISSUE TITLE
Proxy replacement does not work

### ISSUE THREAD

**Issue by Skuriles** [XAMLMarkupExtensions/WPFLocalizeExtension#309]
Hello all, thanks for this extension.

we tried to update to latest version and replace proxy usage as we use a lot of usercontrols.
Idea is to read label texts from json files and set this text to user controls. With the proxy is worked fine.

old
```
<lex:LocProxy
            Source="{Binding LeftText, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type local:DoubleButton}}, Mode=OneWay}"
            x:Name="Proxy" />
<Label Margin="0,0,0,0" Style="{StaticResource Lbl14LightWhiteExp}"
                       Content="{Binding Result, ElementName=Proxy}" />         
```
new:
```
         <Label x:Name="LblContent" x:FieldModifier="private" Style="{StaticResource Lbl14LightWhiteExp}"
                           Margin="0" VerticalAlignment="Center"
                           Content="{lex:Loc {Binding Path=LeftText}}" />

```

`Content="{lex:Loc {Binding LeftText}}` or  ` Content="{lex:Loc {Binding LeftText, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type local:DoubleButton}` did not work, too
Problem: the binding no longer works. It looks like the localization kicks in too early when the property LeftText is not even set, so the Label remains empty. We use propertybindings but this still does not help to get any of the old proxy stuff to work with new binding. So how do we have to create the binding instead of the old proxy?

And another question: Can we prevent the default behavior if label content is emtpy?
We want to use an image instead but as lex:Loc gives back an non-empty string this will not work anymore (e.g. lblContent_Content instead of empty string). We use a ResxLocalizationProvider to handle this cases, but it would be nice to prevent this behavior by default.

Thanks in advance for some advice. 
Regards

**Comment by konne** [comment]
@Skuriles can you provide a small sample app that shows that issues?
Did you even tried the current preRelease?

bye

**Comment by Skuriles** [comment]
Hey, 
think it could be closed.
There was an issue with a parent stackpanel which did not recognize the binding correctly and set it's height to 0. 
=> Without the Stackpanel and the correct settings for ancestors it seems to work.
Sorry for circumstances!

**Comment by konne** [comment]
@Skuriles 
for this issue: And another question: Can we prevent the default behavior if label content is empty?
You can maybe use a converter?

**Comment by Skuriles** [comment]
As said, I use a ResxLocalizationProvider which currently checks for special cases (we used this for proxy upper/lower case writing before). So if no built-in settings is give this solution is fine for us.
As all translations are loaded and rendered at startup we don't need a special converter for this as it is not time-critical or performance affecting.
Thanks
