### ISSUE TITLE
File Version not set for v3.9.0

### ISSUE THREAD

**Issue by strohhaecker** [XAMLMarkupExtensions/WPFLocalizeExtension#316]
Since v3.8.x the File Version is no longer present for the DLLs:
![grafik](https://user-images.githubusercontent.com/46814283/137097504-097fd2fb-fdee-41e1-86e6-1662f2567b07.png)

This causes problems with some setup tools that fail to identify the type of upgrading necessary.

Seems to be related to this commit: https://github.com/XAMLMarkupExtensions/WPFLocalizeExtension/commit/3e713941f39c5d571224951c33dabe8169b95b01

Thanks for any insights!

**Comment by konne** [comment]
@strohhaecker should be fixed in 3.9.1, please check and if you still have an issue, reopen this issue

**Comment by jeremyiverson** [comment]
> @strohhaecker should be fixed in 3.9.1, please check and if you still have an issue, reopen this issue

This is still an issue in 3.9.1

**Comment by konne** [comment]
@jeremyiverson sorry, this was only fixed for the underlaying XamlMarkupExtensions Lib but here we still have an issue. I will check it asap

**Comment by konne** [comment]
@jeremyiverson @strohhaecker now it should be fixed with 3.9.2

![image](https://user-images.githubusercontent.com/1100969/147791724-fece2dcc-6e63-416e-bb50-26d3debcbd96.png)

**Comment by strohhaecker** [comment]
Since we've implemented a work-around for our setup procedure, I cannot directly verify that our problem is fixed.
But both your code changes as well as the resulting changes to the binary indicate that this is no longer an issue, and the ticket can be closed.
Thanks for taking care of this!

**Comment by jeremyiverson** [comment]
I can verify this solves the issue. Thanks so much!
