### ISSUE TITLE
Language reset to default after application startup

### ISSUE THREAD

**Issue by blazcowicz** [XAMLMarkupExtensions/WPFLocalizeExtension#410]
I am working with WPFLocalizeExtension on several projects and it's working like a charm, but we recently discovered a very weird bug. On one of these apps, after the application startup, the current culture is reset to en-US, which causes some issues.

I have tried to debug everything I could, during the application loading the culture was the right one from the appsettings up until the window shows up, then at the first breakpoint I trigger with a button for example, it's back to English. That means the translations based on the value of LocalizeDictionary still work, but some details based on the CultureInfo.CurrentCulture don't (such as names from a list a CultureInfo we need to display).

For context, I am using the following lines of code (that work perfectly fine in the other projects) to setup the application culture during loading : 
`LocalizeDictionary.Instance.SetCurrentThreadCulture = true;
LocalizeDictionary.Instance.Culture = culture;`

I have also checked and everything I've described takes place on the main thread, so that doesn't seem to be the issue. I should also mention that the use of WPFLocalizeExtension on this project is fairly recent, I've implemented it myself to replace a custom obsolete system. I have checked out of curiosity and the bug didn't exist before though, that's what brought me to post here (even though it might be unrelated of course).

So if anyone has ever encountered something similar, I'd be curious to know. Frankly I've run out of things to try or to debug, so even if it's not related to the current extension, I'd be really grateful if anyone could help to solve it.

I am working on Windows 11, the project works with .NET 8.0.

**Comment by Karnah** [comment]
Hi, @blazcowicz!
Sorry, I haven't met such behavior before. Probably somewhere in `xaml` you have `Binding` on `LocalizeDictionary.Instance.Culture`, and this resets value.
I think the best way to debug it: download `WPFLocalizeExtension` source code and use it instead of `Nuget` library. Put breakpoint on `LocalizeDictionary.Instance.Culture` and check all calls. 
I hope it will help.

**Comment by konne** [comment]
@blazcowicz I will close that issue for now, if the answer from @Karnah does not help or your you can describe it more in detail, just reopen the issue.

**Comment by blazcowicz** [comment]
I have tried to use the source code following @Karnah 's suggestion and learned some valuable things about the extension, but it didn't solve my problem. 

Sorry if I wasn't clear enough earlier but there is not issue with `LocalizeDictionary.Instance.Culture`, it's the thread culture and UI culture that changes "on its own". So far I am forced to reset them as soon as possible based on the value from LocalizeDictionary, and I still can't find a single clue about why it's reset, why it wasn't before using this extension or why it doesn't happen in the other projects.

So again I'll be glad if anyone has the slightest idea how this can happen. Thanks for your help so far!

**Comment by Karnah** [comment]
`CultureInfo.CurrentUICulture` and `CultureInfo.CurrentCulture` are thread-dependent. So, if you set `LocalizeDictionary.Instance.Culture` in main thread, these properties will be changed only in main thread. If you create another thread it can have another values. 

So I usually use next pattern:
1. If I need to set culture, I do it only in main thread
2. If I need to get culture, I use `LocalizeDictionary.Instance.Culture`

If you don't use different threads, I don't have an idea. I'd like to ask you to create a small sample project with this problem.

**Comment by Karnah** [comment]
Yes, if you can isolate problem, it will be wonderful. 
Sorry, but I don't have any other ideas now.

**Comment by blazcowicz** [comment]
After a lot more research and a lot of commenting out of code, I have found the difference between this app and the others: the OnStartup method of App.xaml.cs was async, so it seems that if I apply the language here it is not applied to the main thread. If I do it in my constructor or remove the async keyword, it works fine.

The other apps I'm working on don't have an async OnStartup, so they didn't have that issue. Do you have an opinion on which is better for a "standard" WPF app (meaning it's not hosting a background service or anything)? I couldn't really find a clear answer about that in my researches and I have a hard time telling if there's a best practice or not.

**Comment by Karnah** [comment]
Did you mean [this method](https://learn.microsoft.com/en-us/dotnet/api/system.windows.application.onstartup?view=windowsdesktop-8.0)? It has only sync version, so using `async` keyword is not best practice. You can read about `async void` problems [here](https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#avoid-async-void).

You still can use `async void` method, but be careful about thread-dependent parts of code. In some cases you can use [Dispatcher.Invoke](https://learn.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatcher.invoke?view=windowsdesktop-8.0) to run code in the main thread.
