### ISSUE TITLE
Changing LocalizeDictionary.Culture should only change the CurrentUICulture, not the CurrentCulture.

### ISSUE THREAD

**Issue by xlsupport** [XAMLMarkupExtensions/WPFLocalizeExtension#416]
Assume a situation where a user's Culture is different from the UICulture.  Those two cultures may be related like in Switzerland:  de-CH formats and de-DE interface.  Or completely unrelated: local formats nl-NL and English en-US interface.

Some context: I'm developing an Office add-in where I prefer to set localization to that defined by the Host app. I won't be supporting all languages, so I need to give my users a choice for the UI language.  But they'll expect their number & date formats to be familiar.

However: when you set the localizer's Culture to any (supported) value, you'll lose the user's defined formats.

`WPFLocalizeExtension.Engine.LocalizeDictionary.Instance.Culture = "en"`

Imho the problem lies in the setter for the culture property which changes both the CurrentCulture AND the CurrentUICulture 

[src/Engine/LocalizeDictionary.cs](https://github.com/XAMLMarkupExtensions/WPFLocalizeExtension/blob/master/src/Engine/LocalizeDictionary.cs)

Lines  609-627
 ```
 if (_culture != newCulture)
  {
      if (newCulture != null && !MergedAvailableCultures.Contains(newCulture))
          MergedAvailableCultures.Add(newCulture);

      _culture = newCulture;

      // Change the CurrentThread culture if needed.
      if (_setCurrentThreadCulture && !GetIsInDesignMode())
      {
          Thread.CurrentThread.CurrentCulture = _culture;
          Thread.CurrentThread.CurrentUICulture = _culture;
      }

      // Raise the OnLocChanged event
      DictionaryEvent.Invoke(null, new DictionaryEventArgs(DictionaryEventType.CultureChanged, value));

      RaisePropertyChanged(nameof(Culture));
  }
}
```

**Expected behavior**
I think instance.Culture should only change the CurrentUICulture and leave the CurrentCulture alone.
Isn't that the whole idea of the UICulture?

**Known workaround**
Make sure the CurrentThreadCulture is set to the desired value BEFORE changing Instance.Culture

**Enviroment (please complete the following information):**
win11, netfw 4.8.1

**Comment by xlsupport** [comment]
For an extension that focuses on Localization your reaction is disappointing. I respectfully disagree with your  'most cases' and ask you to rethink.  European users will not expect their Euros and 24H clock to be replaced with Dollars and AM/PM just because they choose English for the UI language.  Just saying ;-)

I assume that in most cases developers using WpfLocalize will control culture themselves. Pretty sure of that tbh.

**Comment by Karnah** [comment]
@konne, please, take a look at this situation. I'm really not sure that it's a good idea to change this behavior.

**Comment by xlsupport** [comment]
@Karnah, I agree.  Backward compat makes a change difficult. But adding a Property to synk Culture&UICulture? Make default=true and your  compat is solved.

**Comment by konne** [comment]
@xlsupport I will be honest until now, nobody asked for that feature and we have a lot of companies even in europe that use that library and @Karnah suggested a simple way that should fully solve your issue. Maybe some more lines of code, but nothing complicated. So please just try this way. If you still have an issue, just reach out to us.
If you like you can make a PR that add the suggested behauvior and we will review it. If the PR is small and does not add complexity and is backward compatible I have no issue to merge it.

**Comment by xlsupport** [comment]
No worries. I have my own code that handles the actual culture change before informing WpfLocalize. I'm guessing that many devs do it that way, as it's an easy and obvious workaround.  But it's still a workaround ;-)  

I'm just an old (VB!) hack, and I'll be honest with you: I've got no idea what a PR is. Marketing is in another building ;-)
Feel free to close this issue.
